"""
Django settings for tfg_ps_project project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&66f=r%rxthouo)0l(z)#ooy*@&gqai-_kpgok6j6==&)m63bd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Host permitido para el despliegue

ALLOWED_HOSTS = ['d9ec-81-37-146-116.ngrok-free.app', 'localhost', '127.0.0.1']

# Configuración de CORS

CORS_ALLOWED_ORIGINS = ["https://d9ec-81-37-146-116.ngrok-free.app", ]

# Configuración de CSRF

CSRF_TRUSTED_ORIGINS = ['https://d9ec-81-37-146-116.ngrok-free.app']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tfg_ps_app',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

# Configuración de cookies
SESSION_COOKIE_SECURE = True  # Para usar cookies seguras (solo HTTPS)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expirar sesión al cerrar el navegador
SESSION_COOKIE_AGE = 3600  # Tiempo de vida de la sesión en segundos 

ROOT_URLCONF = 'tfg_ps_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tfg_ps_project.wsgi.application'

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
      'ENGINE': 'django.db.backends.mysql',
      'NAME': 'django_tfg_ps_db',
      'USER': 'root',
      'PASSWORD': '',
      'HOST': 'localhost',
      'PORT': '3306'
    }
  }

# Base de datos en la nube
# DATABASES = {
#     'default': {
#       'ENGINE': 'django.db.backends.mysql',
#       'NAME': 'bh1x3ci2tli0nhamq3zo',
#       'USER': 'ulkh9rcyttvueuze',
#       'PASSWORD': 'j0OfaUUILZKQqbtpJMeI',
#       'HOST': 'bh1x3ci2tli0nhamq3zo-mysql.services.clever-cloud.com',
#       'PORT': '3306'
#     }
#   }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'


# La configuración de MEDIA_URL y MEDIA_ROOT se usa para acceder a los archivos almacenados en la biblioteca os para utilizar la función 
# os.path.join() que permite construir rutas de archivos de manera segura en diferentes sistemas operativos.

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
